### ISSUE TITLE
RHEL8 to RHEL9 Uplift

### ISSUE THREAD

**Issue by rajeeshunikandayil** [oamg/ansible-leapp#245]
Hello Team,

I want to use this automation to uplift our RHEL8 servers to RHEL9. I want to run this in a air gapped environment with local yum repo.
I am not quiet sure what all files I need to modify to use the roles properly. Is there any documentation around this?

**Comment by swapdisk** [comment]
Thank you for your interest in our collection.

Right, you should not need to touch any of your yum repo config files as the roles will take care of this automatically based on the var settings. When you use the `analysis` and `upgrade` roles, you will want to set `leapp_upgrade_type: custom` as well as setting the `local_repos_*` vars documented in the README files for each role. Also look at the comments in the `roles/analysis/defaults/main.yml` and `roles/upgrade/defaults/main.yml` files of the collection where you will find more detailed examples of how to set those `local_repos_*` vars.

Please let me know if this answers your questions?...

**Comment by rajeeshunikandayil** [comment]
We are trying to use this for uplifting RHEL8 box to RHEL9.

On analysis role I added below repositories.

 
leapp_upgrade_type: custom
leapp_repos_enabled:[]                     ->  not sure what we need to give here.
local_repos_pre_leapp:

name:  rhel8-baseos
baseurl: [abc.com](http://abc.com/)
gpgkey: kyc

name: rhel8-appstream
baseurl: [abc.com](http://abc.com/)
gpgkey: kyc

name: rhel8-supplementary
baseurl: [abc.com](http://abc.com/)
gpgkey: kyc

 
name:rhel8-codeready
baseurl: [abc.com](http://abc.com/)
gpgkey: kyc

 

local_repos_leapp:

name:  rhel9-baseos
baseurl: [abc.com](http://abc.com/)
gpgkey: kyc

name: rhel9-appstream
baseurl: [abc.com](http://abc.com/)
gpgkey: kyc
 
name: rhel9-supplementary
baseurl: [abc.com](http://abc.com/)
gpgkey: kyc

name:rhel9-codeready
baseurl: [abc.com](http://abc.com/)
gpgkey: kyc

**Comment by swapdisk** [comment]
If your existing yum configuration already has a repo enabled that includes the leapp packages that need to be installed, you likely don't need to set the `local_repos_pre_leapp` or `local_repos_post_analysis` vars at all. 

The `local_repos_leapp` var should list the repos containing the RHEL package for the target version. If you are upgrading from RHEL8 to RHEL9, it might look something like this example...

```
local_repos_leapp:
  - name: rhel-9-for-x86_64-baseos-rpms
    description: BaseOS for x86_64
    baseurl: https://myrepo.example.com/latest-RHEL-9.6/BaseOS/x86_64/os/
  - name: rhel-9-for-x86_64-appstream-rpms
    description: AppStream for x86_64
    baseurl: https://myrepo.example.com/latest-RHEL-9.6/AppStream/x86_64/os/
```
